name: CICD Pipeline
on:
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: self-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4

      # TRIVY INSTALL
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /usr/share/keyrings/trivy.asc
          echo "deb [signed-by=/usr/share/keyrings/trivy.asc] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy
          
      ## TRIVY (SAFE MODE - NO MAVEN CALLS)
      ##Scan the repository for secrets and misconfigurations, ignore Java/Maven-related files that cause errors, and save the results in a report file.
      - name: Trivy Scan 
        run: |
          trivy fs . \
            --scanners secret,misconfig \
            --skip-files pom.xml \
            --skip-dirs target,.m2 \
            --format table \
            -o trivy-report.json

      - name: Gitleaks installation   
        run: sudo apt install gitleaks -y

      - name: Gitleaks code scan
        run: gitleaks detect --source . -r gitleaks-report.json -f json
        
      
