name: CICD Pipeline

on:
  push:
    branches: ["main"]

jobs:

# ---------------- BUILD + TEST ----------------
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build + Test
        run: mvn clean package

      - name: Verify JAR
        run: ls -la target


# ---------------- SECURITY SCAN ----------------
  security-check:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /usr/share/keyrings/trivy.asc
          echo "deb [signed-by=/usr/share/keyrings/trivy.asc] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: Trivy Scan
        run: |
          trivy fs . \
            --scanners secret,misconfig \
            --skip-files pom.xml \
            --skip-dirs target,.m2 \
            --format table \
            -o trivy-report.json

      - name: Install Gitleaks
        run: sudo apt install gitleaks -y

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source . -r gitleaks-report.json -f json


# ---------------- UNIT TEST ----------------
  unit-test:
    runs-on: self-hosted
    needs: security-check

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run Tests
        run: mvn test


# ---------------- SONAR ----------------
  sonar:
    runs-on: self-hosted
    needs: unit-test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build for Sonar
        run: mvn clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}


# ---------------- DOCKER ----------------
  docker-build:
    runs-on: self-hosted
    needs: sonar

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: saikumar27295/bankapp:latest
